import json
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from app.services.llm import get_llm

def chat_about_contract(
    message: str,
    history: list,
    contract_text: str,
    analysis_report: dict = None,
    user_api_key: str = None
) -> str:
    llm = get_llm(user_api_key)

    if not llm:
        # Demo simulation answers
        msg_lower = message.lower()
        if "missing" in msg_lower or "clause" in msg_lower:
            if analysis_report and "missing_clauses" in analysis_report:
                clauses = [f"- {c['title']}: {c['explanation']}" for c in analysis_report["missing_clauses"]]
                if clauses:
                    return "Based on the demo analysis, the following missing clauses were detected:\n" + "\n".join(clauses)
            return "Based on the demo contract, the confidentiality clause is missing."
        if "liability" in msg_lower or "cap" in msg_lower:
            return "Based on the demo contract, Section 10 caps the vendor's liability at ₹5,00,000. This is unfavorable to the customer compared to the standard requirement, which proposes a cap representing at least 12 months of paid fees."
        if "renewal" in msg_lower or "termination" in msg_lower or "terminate" in msg_lower:
            return "Based on the demo contract, Clause 8 specifies an automatic renewal of the term. It requires a 90-day prior written notice to prevent renewal, which is flagged as a renewal trap (the industry standard is 30 days)."
        if "indemnity" in msg_lower or "indemnify" in msg_lower or "intellectual property" in msg_lower or "ip" in msg_lower:
            return "Section 5 of the contract covers IP Rights. However, this contradicts Section 10's overall ₹5,00,000 cap."
        return "This is a simulated response (Demo Mode). I can answer questions about the demo contract's liability caps (₹5,00,000 limit), renewal terms (90-day auto-renewal notice), and IP contradictions."

    # Live Mode
    max_char_limit = 12000
    safe_contract_text = contract_text
    if len(contract_text) > max_char_limit:
        safe_contract_text = contract_text[:max_char_limit] + "\n\n... [Remaining text truncated] ..."

    report_context = ""
    if analysis_report:
        contract_type = analysis_report.get("contract_type", "Unknown")
        risks = analysis_report.get("risks", [])
        missing = analysis_report.get("missing_clauses", [])
        contradictions = analysis_report.get("contradictions", [])
        
        report_context = (
            "\nHere is the summary of the analysis report generated by the review agent:\n"
            f"- Contract Type: {contract_type}\n"
            f"- Identified Risks: {json.dumps(risks, indent=2)}\n"
            f"- Missing Clauses Detected: {json.dumps(missing, indent=2)}\n"
            f"- Contradictions Detected: {json.dumps(contradictions, indent=2)}\n"
        )

    system_prompt = (
        "You are an expert legal advisor assistant reviewing a contract.\n"
        "Here is the contract text for context:\n"
        f"--- START CONTRACT TEXT ---\n{safe_contract_text}\n--- END CONTRACT TEXT ---\n"
        f"{report_context}\n"
        "Answer the user's questions about this contract objectively, highlighting critical risks or issues where applicable.\n"
        "Be extremely honest: only discuss things that are actually in the contract text or in the analysis report.\n"
        "If a clause is missing, confirm it is missing. Do not claim something exists in the contract if it is not in the text.\n"
        "Keep your response concise, professional, and clear."
    )

    messages = [
        SystemMessage(content=system_prompt)
    ]

    for item in history:
        if item["role"] == "user":
            messages.append(HumanMessage(content=item["content"]))
        else:
            messages.append(AIMessage(content=item["content"]))

    messages.append(HumanMessage(content=message))

    try:
        response = llm.invoke(messages)
        return response.content
    except Exception as e:
        return f"Error communicating with AI: {str(e)}"